### ISSUE TITLE
RLang Version Konflikt

### ISSUE THREAD

**Issue by OliverSchacht** [MattesGrundmann/Addiction-Research#8]
Hi @MattesGrundmann 

folgende Fehlermeldung schien im Code aufzutreten:
`"Namensraum ‘rlang’ 1.0.6 ist bereits geladen, aber  >= 1.1.0 wird gefordert"`.

Ich habe mir gerade den Code angeguckt, bei mir läuft alles durch. Vermutlich, hast du eine alte Version auf deinem PC. Versuch mal
`install.packages("https://cran.r-project.org/src/contrib/Archive/rlang/rlang_1.1.0.tar.gz", repos = NULL, type="source")`
In die Konsole einzugeben.

Noch ein Hinweis zum Code: Ihr müsst nicht jedes Mal alle Pakete installieren. Sobald sie installiert sind, reicht es `library(...)` auszuführen.
Daher würde ich alle `install.packages(...)` am Anfang des Notebooks sammeln und nicht ausführen.

Löst das dein Problem?

**Comment by MattesGrundmann** [comment]
Hi @OliverSchacht, 
danke für Deine schnelle Antwort. 

Leider komme ich auch damit nicht weiter. Hast Du morgen (Dienstag) Zeit, dass wir zusammen drauf schauen?

**Comment by OliverSchacht** [comment]
Bitte versuch nochmal 
`remove.packages(rlang)`
und dann
`install.packages(rlang)`

**Comment by MattesGrundmann** [comment]
Hallo Oliver, 
das hat funktioniert, top danke!
